# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_unmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
