# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_auto_20160612_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='no_photo.jpg', upload_to=b''),
        ),
    ]
